import Head from 'next/head';
import Link from 'next/Link';
import { replies } from '../data';
import { useState } from 'react';

export default function Home() {

  const [locations, setLocations] = useState([])

  function newLocationHandler(event) {
    event.preventDefault();
    const location = {
      name: event.target.locationName.value,
      minCustomers: event.target.minCustomers.value,
      maxCustomers: event.target.maxCustomers.value,
      avgCookies: event.target.avgCookies.value,
      id: locations.length
    };
    setLocations([...locations, location])
  }

  // function getLatestReply() {
  //   if (locations.length === 0) {
  //     return 'Ask a Question!';
  //   }
  //   return locations[locations.length - 1].reply;
  // }

  return (
    <>
      <Head>
          <title>Cookie Stand Admin Page</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='flex items-start p-4 bg-green-300 text-black'>
          <h1>Cookie Stand Admin</h1>
      </header>

      <main className='font-serif'>
          <form className="w-1/2 p-2 mx-auto my-4 bg-green-300" onSubmit={newLocationHandler}>
            <h2 className='text-4xl text-center'>Create Cookie Stand</h2>
            <div className="flex justify-around p-3 my-4">
              <label for="locationName">Location</label>
              <input name="locationName" className="flex-auto pl-1" id="locationName"/>
            </div>
            <div className="flex justify-between">
              <div>
                <label for="minCustomers" className="block p-1">Min Customers/Hour</label>
                <input name="minCustomers" className="block p-1" id="minCustomers"/>
              </div>
              <div>
                <label for="maxCustomers" className="block p-1">Max Customers/Hour</label>
                <input name="maxCustomers" className="block p-1" id="maxCustomers"/>
              </div>
              <div>
                <label for="avgCookies" className="block p-1">Average Cookies/Sale</label>
                <input name="avgCookies" className="block p-1" id="avgCookies"/>
              </div>
              <button className="px-10 py-1 bg-gray-500 text-gray-50 hover:bg-red-500">Create</button>
            </div>
          </form>

          {/* Table of Responses */}
          <table className="w-1/2 mx-auto my-4">
              <thead>
                  <tr>
                      <th className="border border-gray-700">No.</th>
                      <th className="border border-gray-700">Location</th>
                      <th className="border border-gray-700">Minimum Customer/Hour</th>
                      <th className="border border-gray-700">Maximum Customer/Hour</th>
                      <th className="border border-gray-700">Average Cookies/Sale</th>
                  </tr>
              </thead>
              <tbody>
                  {
                    locations.map((item, idx) => {
                      return (
                        <tr key={idx}>
                          <td className="pl-2 border border-gray-700">{item.id}</td>
                          <td className="pl-2 border border-gray-700">{item.name}</td>
                          <td className="pl-2 border border-gray-700">{item.minCustomers}</td>
                          <td className="pl-2 border border-gray-700">{item.maxCustomers}</td>
                          <td className="pl-2 border border-gray-700">{item.avgCookies}</td>
                      </tr>
                      )
                    })
                  }
              </tbody>
          </table>

      </main>

      <footer className='p-4 mt-8 bg-green-300 text-black'>
          <p>&copy; 2023</p>
          <Link href="/careers" className=' text-black hover:text-red-500'>
              Careers
          </Link>
      </footer>
    </>
  );
}
