import Head from 'next/head';
import { useState } from 'react';
import Header from '../components/Header';
import Form from '../components/Form';
import Footer from '../components/Footer';
import Table from '../components/Table';

export default function Home() {

  const [locations, setLocations] = useState([])
  const tableHeaders = ["Location", "6am", "7am", "8am", "9am", "10am", "11am", "12pm", "1pm", "2pm", "3pm", "4pm", "5pm", "6pm", "7pm", "Totals"];

  function newLocationHandler(event) {
    event.preventDefault();
    const location = {
      name: event.target.locationName.value,
      minCustomers: event.target.minCustomers.value,
      maxCustomers: event.target.maxCustomers.value,
      avgCookies: event.target.avgCookies.value,
      id: locations.length
    };
    setLocations([...locations, location])
  }

  return (
    <>
      <Head>
          <title>Cookie Stand Admin Page</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className='font-serif'>
        <Form newLocationHandler={newLocationHandler} />

        <Table locations={locations} />

      </main>

      <Footer locations={locations}/>
    </>
  );
}
